# Generated by Django 3.1.1 on 2020-09-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrition',
            new_name='description',
        ),
    ]
